### PR TITLE
changing the name of the runbook you must also change the json, or all the skripts go kablooey

### PR DESCRIPTION
**Pull request by dougsillars**
There was a name change tp a postgres runbook name, but not the JSON... and all the checks are failing.

### CODE REVIEW

**Review by amit-chandak-unskript — COMMENTED** [review]
Why wasn't it got caught by any checks @dougsillars ???

**Comment by dougsillars** [comment]
> Why wasn't it got caught by any checks @dougsillars ???

do we have runbook checks?

**Comment by amit-chandak-unskript** [comment]
> > Why wasn't it got caught by any checks @dougsillars ???
> 
> do we have runbook checks?

sanitize runbook check

**Comment by abhishek-unskript** [comment]
The name was changed to follow convention : `connector_runbook_name.ipynb`

Current names are all over the place.
Can you provide the exact nature of problem @dougsillars . We need to fix that instead of reverting this change.

**Review by abhishek-unskript — CHANGES_REQUESTED** [review]
We need to make the correct fix here instead of reverting the name change.
We can discuss what needs to be done . I can look into doing it if needed.

**Comment by dougsillars** [comment]
in PR #556, the name of the RunBook was changed, but the name of the JSON that is associated with the RunBook was not changed.  For all actions and runbooks, the json file needs to have the same name as the py/ipynb file.  Because the two files have different names, the scripts that build all of our documentation fail to run.

This PR simply changes the name of the JSON file to match the name of the RunBook.

image

**Comment by amit-chandak-unskript** [comment]
@abhishek-unskript Doug has fixed the runbook name following the convention, so i am merging this, as its breaking our sanity. But the take away is we need to enhance our checks to check. We should be relying on the runbook name inside json, instead of deriving it from the file, otherwise it beats the purpose of having the json.

**Pull request merged**
