### PR TITLE
[RunBook]: Delete NAT Gateways

### PR DESCRIPTION
**Pull request by harshal-netserv**
## Description
Delete Unused NAT Gateways

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published. 

### Documentation
Make sure that you have documented corresponding changes in this repository.

### CODE REVIEW

**Review by dougsillars — APPROVED** [review]

**Comment by amit-chandak-unskript** [comment]
Dont think this runbook is using the right legos. @harshal-netserv we need to revisit this runbook. I will give more details later

**Review by amit-chandak-unskript — CHANGES_REQUESTED** [review]
Dont commit this

**Review by amit-chandak-unskript — DISMISSED** [review]

**Comment by amit-chandak-unskript** [comment]
@shloka-bhalgat-unskript Please take care of the failing check for this PR

**Comment by shloka-bhalgat-unskript** [comment]
Done @amit-chandak-unskript

**Comment by abhishek-unskript** [comment]
Hi @shloka-bhalgat-unskript , is this PR ready to be reviewed again?

**Comment by shloka-bhalgat-unskript** [comment]
@abhishek-unskript we don't need this runbook as it is a duplicate for [this](https://github.com/unskript/Awesome-CloudOps-Automation/blob/master/AWS/AWS_Delete_Unused_NAT_Gateways.ipynb) which is there in our cost-opt suite.

**Comment by shloka-bhalgat-unskript** [comment]
Closing this PR.

**Pull request closed without merging**
